name: Build

on: [push, pull_request]

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      with
        channel: dev
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Test
        run: flutter test --coverage
        working-directory: ${{ matrix.package }}

      - name: Upload to codecov
        run: curl -s https://codecov.io/bash | bash